# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ScoreTableUI.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(805, 608)
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        Form.setFont(font)
        self.baskBtn = QtWidgets.QPushButton(Form)
        self.baskBtn.setGeometry(QtCore.QRect(330, 510, 141, 23))
        self.baskBtn.setObjectName("baskBtn")
        self.widget = QtWidgets.QWidget(Form)
        self.widget.setGeometry(QtCore.QRect(270, 60, 251, 331))
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(24)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.score_1 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(12)
        font.setItalic(False)
        self.score_1.setFont(font)
        self.score_1.setObjectName("score_1")
        self.verticalLayout.addWidget(self.score_1)
        self.score_2 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setItalic(False)
        self.score_2.setFont(font)
        self.score_2.setObjectName("score_2")
        self.verticalLayout.addWidget(self.score_2)
        self.score_3 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setItalic(False)
        self.score_3.setFont(font)
        self.score_3.setObjectName("score_3")
        self.verticalLayout.addWidget(self.score_3)
        self.score_4 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setItalic(False)
        self.score_4.setFont(font)
        self.score_4.setObjectName("score_4")
        self.verticalLayout.addWidget(self.score_4)
        self.score_5 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setItalic(False)
        self.score_5.setFont(font)
        self.score_5.setObjectName("score_5")
        self.verticalLayout.addWidget(self.score_5)
        self.score_6 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setItalic(False)
        self.score_6.setFont(font)
        self.score_6.setObjectName("score_6")
        self.verticalLayout.addWidget(self.score_6)
        self.score_7 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setItalic(False)
        self.score_7.setFont(font)
        self.score_7.setObjectName("score_7")
        self.verticalLayout.addWidget(self.score_7)
        self.score_8 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setItalic(False)
        self.score_8.setFont(font)
        self.score_8.setObjectName("score_8")
        self.verticalLayout.addWidget(self.score_8)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.baskBtn.setText(_translate("Form", "Back"))
        self.label.setText(_translate("Form", "Score Table"))
        self.score_1.setText(_translate("Form", "TextLabel"))
        self.score_2.setText(_translate("Form", "TextLabel"))
        self.score_3.setText(_translate("Form", "TextLabel"))
        self.score_4.setText(_translate("Form", "TextLabel"))
        self.score_5.setText(_translate("Form", "TextLabel"))
        self.score_6.setText(_translate("Form", "TextLabel"))
        self.score_7.setText(_translate("Form", "TextLabel"))
        self.score_8.setText(_translate("Form", "TextLabel"))

